version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - android/run-gradle-command:
          command: androidDependencies
      - android/save-gradle-cache
      - android/run-gradle-command:
          command: build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - android/run-gradle-command:
          command: lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  version: 2
  build-test:
    jobs:
      - build